server:
  port: 8084
spring:
  application:
    name: springcloudconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gyf123456/cloud-config.git
          username: gyf123456
          password: gyf123456789.


eureka:
  client:
    service-url: {"defaultZone":"http://localhost:8080/eureka"}



